# image: https://hub.docker.com/r/portainer/portainer

version: '3.8'

services:
  portainer:
    image: portainer/portainer-${APP_DISTRIBUTION}:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: always
    ports:
      - ${APP_HTTP_PORT}:9000
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  portainer:
